# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: http://mzlogin.github.io
url: http://mzlogin.github.io
date_format: "ordinal"
title: 当然我也在扯淡
author: Zhuang Ma 

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: mazhuang
