# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zsamuelson.github.io
date_format: "ordinal"
title: 健魁
subtitle: "花椒和鱼翅"
description: "健魁学习小屋"
keywords: 记录,学习
timezone: Asia
encoding: "utf-8"
side_bar_repo_limit: 5
repository: ZSamuelson/ZSamuelson.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Zhou jk
organization: 
organization_url: 
github_username: zsamuelson
location: China
email: 3139858123@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于



