# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: http://www.mazhuang.org
url: http://www.mazhuang.org
date_format: "ordinal"
title: 靠谱-ing
author: Zhuang Ma 
paginate: 9

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
#markdown: redcarpet
#redcarpet:
#  extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
pygments: true
permalink: /:year/:month/:day/:title

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: mazhuang
